# -*- coding: utf-8 -*-
"""325: All Stats calculation with Graph  .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uhjlUaS_NtSRxepcS7mxRebIjsuaLoYv
"""

import statistics
import matplotlib.pyplot as plt
from numpy.random import randint

lst = []

for i in range(10):
  j = randint(0,10)
  lst.append(j)
print(f'List of Random Numbers: {lst}')

mean = statistics.mean(lst)
print(f'Mean of Random Numbers: {mean}')

median = statistics.median(lst)
print(f'Median of Random Numbers: {median}')

mode = statistics.mode(lst)
print(f'Mode of Random Numbers: {mode}')

standard_dev = statistics.stdev(lst)
print(f'Standard Deviation of Random Numbers: {standard_dev}')

up_standard_dev = mean + standard_dev
down_standard_dev = mean - standard_dev

q = []
for i in range(len(lst)):
  q.append(up_standard_dev)

r = []
for i in range(len(lst)):
  r.append(down_standard_dev)

s = []
for i in range(len(lst)):
  s.append(mean)

t = []
for i in range(len(lst)):
  t.append(standard_dev)

plt.plot(lst,'b',label='Random Numbers')
plt.plot(q,'r',label = 'Upper Standard Deviation', marker='.',markersize='10')
plt.plot(r,'g',label = 'Lower Standard Deviation', marker='.',markersize='10')
plt.plot(s,'m',label = 'Mean', marker='.',markersize='10')
plt.plot(t,'y',label = 'Standard Deviation', marker='.',markersize='10')

plt.xlabel('X-axis')
plt.ylabel('Y-axis')

plt.legend(bbox_to_anchor =(1.00, 1.15), ncol = 2)
plt.show()